mkdir -p /map/iq/IQ-AP-Invoices-Expense/Fort-Worth-East/Freight
mkdir -p /map/iq/IQ-AP-Invoices-Expense/Fort-Worth-East/Utility
mkdir -p /map/iq/IQ-AP-Invoices-Expense/Fort-Worth-East/Non-Trade
mkdir -p /map/iq/IQ-AP-Invoices-Expense/Fort-Worth-West/Non-Trade
mkdir -p /map/iq/IQ-AP-Invoices-Expense/Fort-Worth-West/Freight
mkdir -p /map/iq/IQ-AP-Invoices-Expense/Fort-Worth-West/Utility
mkdir -p /map/iq/IQ-AP-Invoices-Expense/Greeley/Non-Trade
mkdir -p /map/iq/IQ-AP-Invoices-Expense/Greeley/Utility
mkdir -p /map/iq/IQ-AP-Invoices-Expense/Greeley/Freight
mkdir -p /map/iq/IQ-AP-Invoices-Expense/Dilley/Freight
mkdir -p /map/iq/IQ-AP-Invoices-Expense/Dilley/Utility
mkdir -p /map/iq/IQ-AP-Invoices-Expense/Dilley/Non-Trade
mkdir -p /map/iq/IQ-AP-Invoices-Expense/Dickinson/Utility
mkdir -p /map/iq/IQ-AP-Invoices-Expense/Dickinson/Non-Trade
mkdir -p /map/iq/IQ-AP-Invoices-Expense/Dickinson/Freight
mkdir -p /map/iq/IQ-AP-Invoices-Expense/Casper/Utility
mkdir -p /map/iq/IQ-AP-Invoices-Expense/Casper/Non-Trade
mkdir -p /map/iq/IQ-AP-Invoices-Expense/Casper/Freight
